version: "2"

services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/jenkins_home
      - /Users/zhike/Workspaces:/home/jenkins/repositories
